### ISSUE TITLE
juliaplots.org domain has lapsed

### ISSUE THREAD

**Issue by davidssmith** [JuliaPlots/juliaplots.github.io#1]
Not sure if you want to renew it, or change the README link.

**Comment by ChrisRackauckas** [comment]
No, we just got the domain right now. I'm setting it up right now.

**Comment by ChrisRackauckas** [comment]
The zone edits just haven't gone through yet.

**Comment by davidssmith** [comment]
Oh, ha ha, sorry. Bad timing.

**Comment by ChrisRackauckas** [comment]
Fixed
